import type { Metadata } from "next";
import { Almarai } from "next/font/google";
import "./globals.css";

import { SidebarProvider } from "@/context/SidebarContext";
import { ThemeProvider } from "@/context/ThemeContext";

const almarai = Almarai({
  subsets: ["latin", "arabic"], // or ['latin', 'arabic'] if you want both
  weight: ["300", "400", "700", "800"], // available weights: 300–800
  display: "swap",
  variable: "--font-almarai",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${almarai.variable} ${almarai.variable} antialiased`}>
        <ThemeProvider>
          <SidebarProvider>{children}</SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
